In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
path_2021 = "/content/drive/MyDrive/Mini_ProjectFinalll/data/raw/2021.csv"
df_2021 = pd.read_csv(path_2021)

In [ ]:
df_2021.shape

(3827438, 11)

In [ ]:
df_2021.columns

Index(['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade',
       'Arrival_Date', 'Min_Price', 'Max_Price', 'Modal_Price',
       'Commodity_Code'],
      dtype='object')

In [ ]:
df_2021.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price,Commodity_Code
0,Andhra Pradesh,Chittor,Chittoor,Gur (Jaggery),NO 1,FAQ,2021-01-01,4000.0,4500.0,4000.0,74
1,Andhra Pradesh,Chittor,Mulakalacheruvu,Tomato,Local,FAQ,2021-01-01,550.0,1150.0,850.0,78
2,Andhra Pradesh,Chittor,Vayalapadu,Tomato,Local,FAQ,2021-01-01,360.0,1200.0,800.0,78
3,Andhra Pradesh,Guntur,Tenali,Black Gram (Urd Beans)(Whole),Black Gram (Whole),FAQ,2021-01-01,6300.0,7000.0,6600.0,8
4,Andhra Pradesh,Guntur,Tenali,Lemon,Lemon,FAQ,2021-01-01,1500.0,2200.0,1800.0,310

In [ ]:
df_2021['State'].unique()

array(['Andhra Pradesh', 'Chattisgarh', 'Goa', 'Gujarat', 'Haryana',
       'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka',
       'Kerala', 'Madhya Pradesh', 'Maharashtra', 'NCT of Delhi',
       'Odisha', 'Punjab', 'Rajasthan', 'Tamil Nadu', 'Telangana',
       'Tripura', 'Uttar Pradesh', 'Uttrakhand', 'West Bengal',
       'Meghalaya', 'Nagaland', 'Pondicherry', 'Manipur', 'Assam',
       'Bihar'], dtype=object)

In [ ]:
df_2021['Commodity'].unique()

array(['Gur (Jaggery)', 'Tomato', 'Black Gram (Urd Beans)(Whole)',
       'Lemon', 'Bengal Gram (Gram)(Whole)', 'Jowar (Sorghum)',
       'Paddy (Dhan)(Common)', 'Maize', 'Green Peas',
       'Kodo Millet (Varagu)', 'Lak (Teora)', 'Wheat', 'Corriander seed',
       'Garlic', 'Mahua', 'Turmeric', 'Mustard', 'Apple',
       'Banana - Green', 'Bhindi (Ladies Finger)', 'Bitter gourd',
       'Bottle gourd', 'Brinjal', 'Cabbage', 'Capsicum', 'Carrot',
       'Cauliflower', 'Chikoos (Sapota)', 'Coriander (Leaves)',
       'Cucumbar (Kheera)', 'Ginger (Green)', 'Green Chilli', 'Guar',
       'Guava', 'Knool Khol', 'Little gourd (Kundru)', 'Methi (Leaves)',
       'Mousambi (Sweet Lime)', 'Onion', 'Orange', 'Papaya (Raw)',
       'Pear (Marasebu)', 'Peas Wet', 'Pomegranate', 'Potato', 'Pumpkin',
       'Raddish', 'Tinda', 'Linseed', 'Arecanut (Betelnut/Supari)',
       'Banana', 'Coconut', 'Grapes', 'Marigold (loose)', 'Papaya',
       'Pineapple', 'Water Melon', 'Drumstick', 'Elephant Yam (Suran)',
       'Yam (Ratalu)', 'Arhar (Tur/Red Gram)(Whole)',
       'Bajra (Pearl Millet/Cumbu)', 'Castor Seed', 'Cotton',
       'Cummin Seed (Jeera)', 'Green Gram (Moong)(Whole)',
       'Ground Nut Seed', 'Groundnut', 'Sesamum (Sesame,Gingelly,Til)',
       'Beans', 'Kabuli Chana (Chickpeas-White)',
       'Guar Seed (Cluster Beans Seed)', 'Soanf', 'Isabgul (Psyllium)',
       'Cowpea (Veg)', 'Indian Beans (Seam)', 'Onion Green', 'Peas cod',
       'Pegeon Pea (Arhar Fali)', 'Pointed gourd (Parval)',
       'Ridgeguard (Tori)', 'Sponge gourd', 'Surat Beans (Papadi)',
       'Kulthi (Horse Gram)', 'Mataki', 'Methi Seeds', 'Barley (Jau)',
       'Rice', 'Soyabean', 'Mint (Pudina)', 'Sweet Potato', 'Ajwan',
       'Dry Chillies', 'Suva (Dill Seed)', 'White Peas', 'Cluster beans',
       'Amla (Nelli Kai)', 'French Beans (Frasbean)', 'Spinach',
       'Beetroot', 'Gram Raw (Chholia)', 'Mango (Raw-Ripe)',
       'Round gourd', 'Turmeric (raw)', 'Ginger (Dry)', 'Jack Fruit',
       'Kinnow', 'Turnip', 'Ber (Zizyphus/Borehannu)', 'Leafy Vegetable',
       'Indian Colza (Sarson)', 'Colacasia', 'Mashrooms', 'Field Pea',
       'Sunflower', 'Alasande Gram', 'Arhar Dal (Tur Dal)', 'Avare Dal',
       'Bengal Gram Dal (Chana Dal)', 'Black Gram Dal (Urd Dal)',
       'Chennangi Dal', 'Foxtail Millet (Navane)',
       'Green Gram Dal (Moong Dal)', 'Ragi (Finger Millet)',
       'Tamarind Fruit', 'Alsandikai', 'Bunch Beans', 'Chapparad Avare',
       'Green Avare (W)', 'Karbuja (Musk Melon)', 'Lime', 'Seemebadnekai',
       'Snakeguard', 'Suvarna Gadde', 'Thondekai', 'Betal Leaves',
       'Chilly Capsicum', 'Sweet Pumpkin', 'Thogrikai',
       'Cowpea (Lobia/Karamani)', 'Safflower', 'Same/Savi', 'Bull',
       'Calf', 'Cow', 'She Buffalo', 'Sajje', 'Ox', 'Duster Beans',
       'Copra', 'Black pepper', 'Tender Coconut', 'Ashgourd', 'Chili Red',
       'White Pumpkin', 'Amaranthus', 'Amphophalus', 'Tapioca', 'Mango',
       'Coconut Oil', 'Coconut Seed', 'Cardamoms', 'Cloves', 'Nutmeg',
       'Rubber', 'Cashewnuts', 'Pepper garbled', 'Long Melon (Kakri)',
       'Egg', 'Pepper ungarbled', 'Soji', 'Coffee',
       'Lentil (Masur)(Whole)', 'Paddy (Dhan)(Basmati)', 'Peas (Dry)',
       'Masur Dal', 'Sugar', 'Seetapal', 'Plum', 'Rajgir', 'Cock', 'Fish',
       'Hen', 'BOP', 'Carnation', 'Chrysanthemum',
       'Chrysanthemum (Loose)', 'Delha', 'Gladiolus Cut Flower', 'Jaffri',
       'Jarbara', 'Lilly', 'Lotus', 'Marget', 'Marigold (Calcutta)',
       'Patti Calcutta', 'Rose (Local)', 'Rose (Loose))',
       'Tube Rose (Double)', 'Tube Rose (Single)', 'Goat', 'Broken Rice',
       'Galgal (Lemon)', 'Season Leaves', 'Taramira', 'Moath Dal',
       'Mahedi', 'Pigs', 'Squash (Chappal Kadoo)', 'Ghee', 'Mustard Oil',
       'Bran', 'Maida Atta', 'Wheat Atta', 'Gramflour', 'Khoya', 'Jute',
       'Borehannu', 'Dry Grapes', 'Sheep', 'Gurellu', 'Gingelly Oil',
       'Sabu Dan', 'Other Pulses', 'Bay leaf (Tejpatta)', 'Anthorium',
       'Dhaincha', 'Ram', 'He Buffalo', 'Yam', 'Tamarind Seed',
       'Sugarcane', 'Groundnut (Split)', 'Dry Fodder', 'Hippe Seed',
       'Resinwood', 'Orchid', 'Chow Chow', 'Neem Seed', 'T.V. Cumbu',
       'Cocoa', 'Broomstick (Flower Broom)', 'Almond (Badam)', 'Tobacco',
       'Niger Seed (Ramtil)', 'Coca', 'Daila (Chandni)', 'Bamboo',
       'Mahua Seed (Hippe seed)', 'Groundnut pods (raw)', 'Toria',
       'She Goat', 'Ambada Seed', 'Rat Tail Radish (Mogari)', 'Duck',
       'Dalda', 'Soapnut (Antawala/Retha)', 'Millets', 'Green Fodder',
       'Lint', 'Astera', 'Honge seed', 'Beaten Rice', 'Jasmine', 'Raibel',
       'Cotton Seed', 'Antawala', 'Butter', 'Bullar', 'Lukad',
       'Tube Rose (Loose)', 'Thinai (Italian Millet)', 'Siddota',
       'Sunhemp', 'Peach', 'Litchi', 'Jamun (Narale Hannu)',
       'Myrobolan (Harad)', 'Wood', 'Javi', 'Kartali (Kantola)',
       'Skin And Hide', 'Cherry', 'Apricot (Jardalu/Khumani)',
       'Lotus Sticks', 'Mace', 'Cane', 'Custard Apple (Sharifa)',
       'Persimon (Japani Fal)', 'Karamani', 'Marasebu'], dtype=object)

In [ ]:
df_2021['Arrival_Date'] = pd.to_datetime(df_2021['Arrival_Date'])

In [ ]:
df_2021['Arrival_Date'].min(), df_2021['Arrival_Date'].max()

(Timestamp('2021-01-01 00:00:00'), Timestamp('2021-12-31 00:00:00'))

In [ ]:
df_2021['Arrival_Date'].isnull().sum()

np.int64(0)

In [ ]:
south_states = ['Telangana', 'Andhra Pradesh']

df_2021_south = df_2021[df_2021['State'].isin(south_states)]

In [ ]:
df_2021_south.shape

(66589, 11)

In [ ]:
df_2021['Commodity'].nunique()

291

In [ ]:
selected_commodities = [
    'Gur (Jaggery)',
    'Black Gram (Urd Beans)(Whole)',
    'Bengal Gram (Gram)(Whole)',
    'Jowar (Sorghum)',
    'Paddy (Dhan)(Common)',
    'Kodo Millet (Varagu)',
    'Wheat',
    'Corriander seed',
    'Garlic',
    'Turmeric',
    'Mustard',
    'Banana - Green',
    'Ginger (Green)',
    'Onion',
    'Orange',
    'Potato',
    'Pumpkin',
    'Linseed',
    'Arecanut (Betelnut/Supari)',
    'Coconut',
    'Elephant Yam (Suran)',
    'Yam (Ratalu)',
    'Arhar (Tur/Red Gram)(Whole)',
    'Bajra (Pearl Millet/Cumbu)',
    'Castor Seed',
    'Cotton',
    'Cummin Seed (Jeera)',
    'Green Gram (Moong)(Whole)',
    'Ground Nut Seed',
    'Groundnut',
    'Sesamum (Sesame,Gingelly,Til)',
    'Kabuli Chana (Chickpeas-White)',
    'Soanf',
    'Cowpea (Veg)',
    'Peas cod',
    'Pegeon Pea (Arhar Fali)',
    'Kulthi (Horse Gram)',
    'Methi Seeds',
    'Barley (Jau)',
    'Rice',
    'Soyabean',
    'Sweet Potato',
    'Ajwan',
    'Dry Chillies',
    'Amla (Nelli Kai)',
    'Beetroot',
    'Gram Raw (Chholia)',
    'Turmeric (raw)',
    'Ginger (Dry)',
    'Turnip',
    'Colacasia',
    'Sunflower',
    'Alasande Gram',
    'Arhar Dal (Tur Dal)',
    'Avare Dal',
    'Bengal Gram Dal (Chana Dal)',
    'Black Gram Dal (Urd Dal)',
    'Chennangi Dal',
    'Foxtail Millet (Navane)',
    'Green Gram Dal (Moong Dal)',
    'Ragi (Finger Millet)',
    'Tamarind Fruit',
    'Bull',
    'Copra',
    'Black pepper',
    'Tender Coconut',
    'Coconut Oil',
    'Coconut Seed',
    'Cardamoms',
    'Cloves',
    'Nutmeg',
    'Cashewnuts',
    'Egg',
    'Lentil (Masur)(Whole)',
    'Paddy (Dhan)(Basmati)',
    'Masur Dal',
    'Sugar',
    'Broken Rice',
    'Ghee',
    'Mustard Oil',
    'Bran',
    'Maida Atta',
    'Wheat Atta',
    'Gramflour',
    'Dry Grapes',
    'Sabu Dan',
    'Bay leaf (Tejpatta)',
    'Groundnut (Split)',
    'Almond (Badam)',
    'Tobacco',
    'Niger Seed (Ramtil)',
    'Dalda',
    'Soapnut (Antawala/Retha)',
    'Beaten Rice',
    'Thinai (Italian Millet)'
]

In [ ]:
df_2021_filtered = df_2021_south[
    df_2021_south['Commodity'].isin(selected_commodities)
]

In [ ]:
print("Original rows:", df_2021.shape)
print("Filtered rows:", df_2021_filtered.shape)

Original rows: (3827438, 11)
Filtered rows: (31648, 11)

In [ ]:
df_2021_filtered['Commodity'].unique()

array(['Gur (Jaggery)', 'Black Gram (Urd Beans)(Whole)',
       'Bengal Gram (Gram)(Whole)', 'Jowar (Sorghum)',
       'Paddy (Dhan)(Common)', 'Onion', 'Potato',
       'Arhar (Tur/Red Gram)(Whole)', 'Castor Seed', 'Dry Chillies',
       'Groundnut', 'Sunflower', 'Cotton', 'Soyabean', 'Ajwan',
       'Beetroot', 'Colacasia', 'Pumpkin', 'Sweet Potato', 'Yam (Ratalu)',
       'Turmeric', 'Green Gram (Moong)(Whole)',
       'Black Gram Dal (Urd Dal)', 'Amla (Nelli Kai)', 'Wheat', 'Garlic',
       'Sesamum (Sesame,Gingelly,Til)', 'Rice', 'Banana - Green',
       'Paddy (Dhan)(Basmati)', 'Elephant Yam (Suran)',
       'Foxtail Millet (Navane)'], dtype=object)

In [ ]:
df_2021_filtered['State'].unique()

array(['Andhra Pradesh', 'Telangana'], dtype=object)

In [ ]:
df_2021_filtered.shape

(31648, 11)

In [ ]:
df_2021_filtered.shape
df_2021_filtered['State'].unique()
df_2021_filtered['Commodity'].unique()

array(['Gur (Jaggery)', 'Black Gram (Urd Beans)(Whole)',
       'Bengal Gram (Gram)(Whole)', 'Jowar (Sorghum)',
       'Paddy (Dhan)(Common)', 'Onion', 'Potato',
       'Arhar (Tur/Red Gram)(Whole)', 'Castor Seed', 'Dry Chillies',
       'Groundnut', 'Sunflower', 'Cotton', 'Soyabean', 'Ajwan',
       'Beetroot', 'Colacasia', 'Pumpkin', 'Sweet Potato', 'Yam (Ratalu)',
       'Turmeric', 'Green Gram (Moong)(Whole)',
       'Black Gram Dal (Urd Dal)', 'Amla (Nelli Kai)', 'Wheat', 'Garlic',
       'Sesamum (Sesame,Gingelly,Til)', 'Rice', 'Banana - Green',
       'Paddy (Dhan)(Basmati)', 'Elephant Yam (Suran)',
       'Foxtail Millet (Navane)'], dtype=object)

In [ ]:
df_2021_filtered[['Min_Price','Max_Price','Modal_Price']].describe()

          Min_Price     Max_Price   Modal_Price
count  31648.000000  31648.000000  31648.000000
mean    2739.924349   3289.450551   3101.104280
std     1854.780628   2392.660465   2083.029801
min        0.000000      0.000000    100.000000
25%     1800.000000   1888.000000   1868.000000
50%     1940.000000   1960.000000   1960.000000
75%     3610.000000   4700.000000   4600.000000
max    14555.000000  28080.000000  18818.000000

In [ ]:
df_2021_filtered.duplicated().sum()

np.int64(0)

In [ ]:
# Optional backup (NOT mandatory)
df_2021_filtered.to_csv(
    "/content/drive/MyDrive/Mini_ProjectFinalll/data/processed/backup_2021.csv",
    index=False
)

In [ ]:
path_2022 = "/content/drive/MyDrive/Mini_ProjectFinalll/data/raw/2022.csv"
df_2022 = pd.read_csv(path_2022)

In [ ]:
df_2022.shape

(4476890, 11)

In [ ]:

df_2022['Commodity'].nunique()

297

In [ ]:
df_2022['Commodity'].unique()

array(['Gur (Jaggery)', 'Tomato', 'Beetroot', 'Bhindi (Ladies Finger)',
       'Bitter gourd', 'Bottle gourd', 'Brinjal', 'Carrot', 'Cauliflower',
       'Cluster beans', 'Cucumbar (Kheera)', 'Green Chilli', 'Potato',
       'Raddish', 'Banana', 'Black Gram (Urd Beans)(Whole)', 'Lemon',
       'Jowar (Sorghum)', 'Paddy (Dhan)(Common)', 'Rice', 'Maize',
       'Bengal Gram (Gram)(Whole)', 'Arhar (Tur/Red Gram)(Whole)',
       'Onion', 'Lime', 'Papaya', 'Round gourd', 'Dry Chillies', 'Apple',
       'Banana - Green', 'Cabbage', 'Capsicum', 'Chikoos (Sapota)',
       'Coriander (Leaves)', 'Garlic', 'Ginger (Green)', 'Grapes', 'Guar',
       'Little gourd (Kundru)', 'Methi (Leaves)', 'Mousambi (Sweet Lime)',
       'Orange', 'Papaya (Raw)', 'Peas Wet', 'Pomegranate', 'Pumpkin',
       'Soyabean', 'Wheat', 'Mahua', 'Lak (Teora)',
       'Arecanut (Betelnut/Supari)', 'Coconut', 'Pineapple',
       'Water Melon', 'Amla (Nelli Kai)', 'Drumstick',
       'Elephant Yam (Suran)', 'Onion Green', 'Rat Tail Radish (Mogari)',
       'Sweet Potato', 'Turmeric (raw)', 'Yam (Ratalu)', 'Amaranthus',
       'Mint (Pudina)', 'Spinach', 'Castor Seed', 'Cotton', 'Ajwan',
       'Bajra (Pearl Millet/Cumbu)', 'Corriander seed',
       'Cummin Seed (Jeera)', 'Green Gram (Moong)(Whole)',
       'Ground Nut Seed', 'Groundnut', 'Methi Seeds',
       'Sesamum (Sesame,Gingelly,Til)', 'Kulthi (Horse Gram)',
       'Kabuli Chana (Chickpeas-White)', 'Moath Dal', 'Mustard',
       'Peas cod', 'Guava', 'Cowpea (Lobia/Karamani)',
       'Guar Seed (Cluster Beans Seed)', 'Suva (Dill Seed)', 'Rajgir',
       'Surat Beans (Papadi)', 'Mataki', 'Barley (Jau)', 'Green Peas',
       'French Beans (Frasbean)', 'Pegeon Pea (Arhar Fali)',
       'Groundnut (Split)', 'Isabgul (Psyllium)', 'Soanf',
       'Ber (Zizyphus/Borehannu)', 'Beans', 'Pointed gourd (Parval)',
       'Cowpea (Veg)', 'Indian Beans (Seam)', 'Mango (Raw-Ripe)',
       'Ridgeguard (Tori)', 'Sponge gourd', 'Tinda', 'Gram Raw (Chholia)',
       'Leafy Vegetable', 'Dry Fodder', 'Green Fodder', 'Kinnow',
       'Turnip', 'Ginger (Dry)', 'Paddy (Dhan)(Basmati)',
       'Karbuja (Musk Melon)', 'Indian Colza (Sarson)', 'Colacasia',
       'Mashrooms', 'Squash (Chappal Kadoo)', 'Knool Khol',
       'Lotus Sticks', 'Tender Coconut', 'Field Pea', 'Sunflower',
       'Alasande Gram', 'Arhar Dal (Tur Dal)', 'Avare Dal',
       'Bengal Gram Dal (Chana Dal)', 'Black Gram Dal (Urd Dal)',
       'Chennangi Dal', 'Copra', 'Green Gram Dal (Moong Dal)',
       'Ragi (Finger Millet)', 'Tamarind Fruit', 'Turmeric', 'Alsandikai',
       'Bunch Beans', 'Chapparad Avare', 'Green Avare (W)',
       'Seemebadnekai', 'Snakeguard', 'Suvarna Gadde', 'Thondekai',
       'White Pumpkin', 'Betal Leaves', 'Dry Grapes', 'Same/Savi',
       'Ashgourd', 'Seetapal', 'Thogrikai', 'Safflower', 'Sajje',
       'Black pepper', 'Chilly Capsicum', 'Chrysanthemum (Loose)',
       'Marigold (Calcutta)', 'Rose (Loose))', 'Foxtail Millet (Navane)',
       'Sweet Pumpkin', 'Chili Red', 'Amphophalus', 'Tapioca', 'Mango',
       'Egg', 'Pepper ungarbled', 'Yam', 'Cardamoms', 'Cloves', 'Cocoa',
       'Coconut Oil', 'Nutmeg', 'Rubber', 'Coconut Seed', 'Cashewnuts',
       'Pepper garbled', 'Long Melon (Kakri)', 'Hen', 'Jasmine',
       'Duster Beans', 'Coffee', 'Kodo Millet (Varagu)', 'Linseed',
       'Lentil (Masur)(Whole)', 'Peas (Dry)', 'Niger Seed (Ramtil)',
       'Masur Dal', 'Taramira', 'Ghee', 'Sabu Dan', 'Sugar', 'Cow',
       'Goat', 'He Buffalo', 'Ox', 'She Buffalo', 'Hippe Seed',
       'Season Leaves', 'Cock', 'Fish', 'Anthorium', 'BOP', 'Carnation',
       'Gladiolus Cut Flower', 'Jaffri', 'Jarbara', 'Lilly', 'Lotus',
       'Marget', 'Rose (Local)', 'Tube Rose (Double)',
       'Tube Rose (Single)', 'Galgal (Lemon)', 'Dhaincha', 'Cotton Seed',
       'Balekai', 'Marigold (loose)', 'Chow Chow', 'Kankambra', 'Wood',
       'Calf', 'Duck', 'Pigs', 'Mustard Oil', 'White Peas', 'Jute',
       'Tube Rose (Loose)', 'Sugarcane', 'Ram', 'Sheep', 'Bull',
       'She Goat', 'Jack Fruit', 'Pear (Marasebu)', 'Chrysanthemum',
       'Orchid', 'Hybrid Cumbu', 'Toria', 'Tamarind Seed', 'Millets',
       'Neem Seed', 'Plum', 'Bay leaf (Tejpatta)', 'T.V. Cumbu',
       'Thinai (Italian Millet)', 'Mahedi', 'Gingelly Oil',
       'Groundnut pods (raw)', 'Wheat Atta', 'Mahua Seed (Hippe seed)',
       'Soapnut (Antawala/Retha)', 'Sunhemp', 'Soji', 'Bran',
       'Maida Atta', 'Gramflour', 'Khoya', 'Tobacco', 'Butter',
       'Jamun (Narale Hannu)', 'Litchi', 'Broken Rice',
       'Broomstick (Flower Broom)', 'Mace', 'Raibel', 'Astera',
       'Almond (Badam)', 'Patti Calcutta', 'Cinamon (Dalchini)',
       'Myrobolan (Harad)', 'Raya', 'Ambada Seed', 'Resinwood', 'Suram',
       'Firewood', 'Karamani', 'Honge seed', 'Antawala', 'Bamboo',
       'Peach', 'Wool', 'Lukad', 'Gurellu', 'Cherry',
       'Persimon (Japani Fal)', 'Kacholam', 'Dalda', 'Lint',
       'Kartali (Kantola)', 'Beaten Rice', 'Apricot (Jardalu/Khumani)',
       'Fig (Anjura/Anjeer)', 'Ground Nut Oil', 'Marasebu', 'Binoula',
       'Kakada', 'Custard Apple (Sharifa)', 'Walnut', 'Borehannu', 'Tea'],
      dtype=object)

In [ ]:
df_2022['Arrival_Date'] = pd.to_datetime(df_2022['Arrival_Date'])

In [ ]:
south_states = ['Telangana', 'Andhra Pradesh']

df_2022_south = df_2022[df_2022['State'].isin(south_states)]

In [ ]:
selected_commodities = [
    'Gur (Jaggery)',
    'Black Gram (Urd Beans)(Whole)',
    'Bengal Gram (Gram)(Whole)',
    'Jowar (Sorghum)',
    'Paddy (Dhan)(Common)',
    'Kodo Millet (Varagu)',
    'Wheat',
    'Corriander seed',
    'Garlic',
    'Turmeric',
    'Mustard',
    'Banana - Green',
    'Ginger (Green)',
    'Onion',
    'Orange',
    'Potato',
    'Pumpkin',
    'Linseed',
    'Arecanut (Betelnut/Supari)',
    'Coconut',
    'Elephant Yam (Suran)',
    'Yam (Ratalu)',
    'Arhar (Tur/Red Gram)(Whole)',
    'Bajra (Pearl Millet/Cumbu)',
    'Castor Seed',
    'Cotton',
    'Cummin Seed (Jeera)',
    'Green Gram (Moong)(Whole)',
    'Ground Nut Seed',
    'Groundnut',
    'Sesamum (Sesame,Gingelly,Til)',
    'Kabuli Chana (Chickpeas-White)',
    'Soanf',
    'Cowpea (Veg)',
    'Peas cod',
    'Pegeon Pea (Arhar Fali)',
    'Kulthi (Horse Gram)',
    'Methi Seeds',
    'Barley (Jau)',
    'Rice',
    'Soyabean',
    'Sweet Potato',
    'Ajwan',
    'Dry Chillies',
    'Amla (Nelli Kai)',
    'Beetroot',
    'Gram Raw (Chholia)',
    'Turmeric (raw)',
    'Ginger (Dry)',
    'Turnip',
    'Colacasia',
    'Sunflower',
    'Alasande Gram',
    'Arhar Dal (Tur Dal)',
    'Avare Dal',
    'Bengal Gram Dal (Chana Dal)',
    'Black Gram Dal (Urd Dal)',
    'Chennangi Dal',
    'Foxtail Millet (Navane)',
    'Green Gram Dal (Moong Dal)',
    'Ragi (Finger Millet)',
    'Tamarind Fruit',
    'Bull',
    'Copra',
    'Black pepper',
    'Tender Coconut',
    'Coconut Oil',
    'Coconut Seed',
    'Cardamoms',
    'Cloves',
    'Nutmeg',
    'Cashewnuts',
    'Egg',
    'Lentil (Masur)(Whole)',
    'Paddy (Dhan)(Basmati)',
    'Masur Dal',
    'Sugar',
    'Broken Rice',
    'Ghee',
    'Mustard Oil',
    'Bran',
    'Maida Atta',
    'Wheat Atta',
    'Gramflour',
    'Dry Grapes',
    'Sabu Dan',
    'Bay leaf (Tejpatta)',
    'Groundnut (Split)',
    'Almond (Badam)',
    'Tobacco',
    'Niger Seed (Ramtil)',
    'Dalda',
    'Soapnut (Antawala/Retha)',
    'Beaten Rice',
    'Thinai (Italian Millet)'
]

In [ ]:
df_2022_filtered = df_2022_south[
    df_2022_south['Commodity'].isin(selected_commodities)
]

In [ ]:
print(df_2022_filtered.shape)

(79813, 11)

In [ ]:
# Optional backup (NOT mandatory)
df_2022_filtered.to_csv(
    "/content/drive/MyDrive/Mini_ProjectFinalll/data/processed/backup_2022.csv",
    index=False
)

In [ ]:
path_2023 = "/content/drive/MyDrive/Mini_ProjectFinalll/data/raw/2023.csv"
df_2023 = pd.read_csv(path_2023)

In [ ]:
df_2023.shape

(4415690, 11)

In [ ]:
df_2023['Commodity'].nunique()

298

In [ ]:
df_2023['Arrival_Date'] = pd.to_datetime(df_2023['Arrival_Date'])

In [ ]:
south_states = ['Telangana', 'Andhra Pradesh']

df_2023_south = df_2023[df_2023['State'].isin(south_states)]

In [ ]:

df_2023_filtered = df_2023_south[
    df_2023_south['Commodity'].isin(selected_commodities)
]

In [ ]:
print(df_2023_filtered.shape)

(77889, 11)

In [ ]:
# Optional backup (NOT mandatory)
df_2023_filtered.to_csv(
    "/content/drive/MyDrive/Mini_ProjectFinalll/data/processed/backup_2023.csv",
    index=False
)

In [ ]:
path_2024 = "/content/drive/MyDrive/Mini_ProjectFinalll/data/raw/2024.csv"
df_2024 = pd.read_csv(path_2024)

In [ ]:
df_2024.shape

(5544500, 11)

In [ ]:
df_2024['Commodity'].nunique()

320

In [ ]:
df_2024['Arrival_Date'] = pd.to_datetime(df_2024['Arrival_Date'])

In [ ]:
south_states = ['Telangana', 'Andhra Pradesh']

df_2024_south = df_2024[df_2024['State'].isin(south_states)]

In [ ]:
df_2024_filtered = df_2024_south[
    df_2024_south['Commodity'].isin(selected_commodities)
]

In [ ]:
print(df_2024_filtered.shape)

(53029, 11)

In [ ]:
# Optional backup (NOT mandatory)
df_2024_filtered.to_csv(
    "/content/drive/MyDrive/Mini_ProjectFinalll/data/processed/backup_2024.csv",
    index=False
)

In [ ]:
path_2025 = "/content/drive/MyDrive/Mini_ProjectFinalll/data/raw/2025.csv"
df_2025 = pd.read_csv(path_2025)

In [ ]:
df_2025.shape

(5819482, 11)

In [ ]:
df_2025['Commodity'].nunique()

338

In [ ]:
df_2025['Arrival_Date'] = pd.to_datetime(df_2025['Arrival_Date'])

In [ ]:
south_states = ['Telangana', 'Andhra Pradesh']

df_2025_south = df_2025[df_2025['State'].isin(south_states)]

In [ ]:
df_2025_filtered = df_2025_south[
    df_2025_south['Commodity'].isin(selected_commodities)
]

In [ ]:
print(df_2025_filtered.shape)

(40123, 11)

In [ ]:
df_2025_filtered.to_csv(
    "/content/drive/MyDrive/Mini_ProjectFinalll/data/processed/backup_2025.csv",
    index=False
)

In [ ]:
path_2020 = "/content/drive/MyDrive/Mini_ProjectFinalll/data/raw/2020.csv"
df_2020 = pd.read_csv(path_2020)

In [ ]:
df_2020.shape

(3548553, 11)

In [ ]:
df_2020['Commodity'].nunique()

292

In [ ]:
df_2020['Arrival_Date'] = pd.to_datetime(df_2020['Arrival_Date'])

In [ ]:
south_states = ['Telangana', 'Andhra Pradesh']

df_2020_south = df_2020[df_2020['State'].isin(south_states)]

In [ ]:
df_2020_filtered = df_2020_south[
    df_2020_south['Commodity'].isin(selected_commodities)
]

In [ ]:
print(df_2020_filtered.shape)

(17221, 11)

In [ ]:
df_2020_filtered.to_csv(
    "/content/drive/MyDrive/Mini_ProjectFinalll/data/processed/backup_2020.csv",
    index=False
)

In [ ]:
df_all_years = pd.concat([
    df_2021_filtered,
    df_2022_filtered,
    df_2023_filtered,
    df_2024_filtered,
    df_2025_filtered,
    df_2020_filtered
], ignore_index=True)

In [ ]:
df_all_years.shape

(299723, 11)

In [ ]:

df_all_years['Arrival_Date'].min()

Timestamp('2020-01-01 00:00:00')

In [ ]:
df_all_years['Arrival_Date'].max()

Timestamp('2025-12-29 00:00:00')

In [ ]:
save_path = "/content/drive/MyDrive/Mini_ProjectFinalll/data/processed/south_india_commodities_2020_2025.csv"
df_all_years.to_csv(save_path, index=False)